version: "3.3"

services:
  app:
    image: containous/whoami
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.docker.network=traefik"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:devx.lt"
        - "traefik.port=80"
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
    networks:
      - default
      - traefik

networks:
  traefik:
    external: true
